# Linear Algebra Playbook

<p>
Mal Minhas, v0.2<br>
30.12.22
</p>

## Introduction

Numerous problems in engineering and science can be described or approximated by linear relationships.  The study of linear relationship is contained in the field of **linear algebra**.

## Vectors

The set ${\mathbb{R}}^n$ is the set of all 𝑛-tuples of real numbers. In set notation this is ${\mathbb{R}}^n = \{(x_1,x_2,x_3,...,x_n):x_1,x_2,x_3,...,x_n{\in}{\mathbb{R}}^n\}$. For example, the set ${\mathbb{R}}^3$ represents the set of real triples, $({x},{y},{z})$ coordinates, in three-dimensional space.

A vector in ${\mathbb{R}}^n$ is an ${n}$-tuple, or point, in ${\mathbb{R}}^n$. Vectors can be written horizontally (i.e., with the elements of the vector next to each other) in a **row vector**, or vertically (i.e., with the elements of the vector on top of each other) in a **column vector**. If the context of a vector is ambiguous, it usually means the vector is a column vector. The ${i}$-th element of a vector, ${v}$, is denoted by  ${v}_i$. The transpose of a column vector is a row vector of the same length, and the transpose of a row vector is a column vector. In mathematics, the transpose is denoted by a superscript ${T}$, or  ${v}^T$. The zero vector is the vector in ${\mathbb{R}}^n$ containing all zeros.  The following Python code creates a row vector and a separate column vector, and shows the shape of the vectors.

In [1]:
import numpy as np
row_vector = np.array([[1, -5, 3, 2, 4]])
column_vector = np.array([[1], 
                          [2], 
                          [3], 
                          [4]])
print(f'row_vector of shape {row_vector.shape}:\n{row_vector}')
print(f'column_vector of shape {column_vector.shape}:\n{column_vector}')

row_vector of shape (1, 5):
[[ 1 -5  3  2  4]]
column_vector of shape (4, 1):
[[1]
 [2]
 [3]
 [4]]


The **norm** of a vector is a measure of its length. There are many ways of defining the length of a vector depending on the metric used (i.e., the distance formula chosen). The most common is called the **$L_2$ norm**, which is computed according to the distance formula you are probably familiar with from school. The $L_2$ norm of a vector $v$ is denoted by $||{v}||_2$ and $||{v}|| = \sqrt{{\sum_i}{v_i^2}}$. This is sometimes also called Euclidian length and refers to the “physical” length of a vector in 1-D, 2-D, or 3-D space. The **$L_1$ norm**, or “Manhattan Distance,” is computed as $||{v}||_1 = {\sum_i}|{v_i}|$, and is named after the grid-like road structure in New York City. The **p-norm**, $L_p$, of a vector is $||{v}||_p = \sqrt[p]{{\sum_i}{v_i^p}}$. The **$L_\infty$ norm**, where $p=\infty$ is written as $||𝑣||_\infty$.  The $L_\infty$ norm is equal to the maximum absolute value in $v$.

Here we transpose the row vector defined above into a column vector and calculate its $L_1$, $L_2$, and $L_\infty$ norms:

In [2]:
from numpy.linalg import norm
new_vector = row_vector.T
print(f'column_vector of shape {new_vector.shape}:\n{new_vector}')
norm_1 = norm(new_vector, 1)
norm_2 = norm(new_vector, 2)
norm_inf = norm(new_vector, np.inf)
print(f'L_1 norm is: {norm_1:.1f}')
print(f'L_2 norm is: {norm_2:.1f}')
print(f'L_inf norm is: {norm_inf:.1f}')

column_vector of shape (5, 1):
[[ 1]
 [-5]
 [ 3]
 [ 2]
 [ 4]]
L_1 norm is: 15.0
L_2 norm is: 7.4
L_inf norm is: 5.0


**Vector addition** is defined as the pairwise addition of each of the elements of the added vectors. For example, if $v$ and $w$ are vectors in ${\mathbb{R}}^n$, then $u=v+w$ is defined as $u_i=v_i+w_i$.

**Vector multiplication** can be defined in several ways depending on the context. **Scalar multiplication** of a vector is the product of a vector and a scalar (i.e., a number in ${\mathbb{R}}^n$). Scalar multiplication is defined as the product of each element of the vector by the scalar. More specifically, if $\alpha$ is a scalar and $v$ is a vector, then 
$u = \alpha{v}$ is defined as $u_i = \alpha{v_i}$. Note that this is exactly how Python implements scalar multiplication with a vector.

The **dot product** of two vectors is the sum of the product of the respective elements in each vector and is denoted by $.$, and $v.{w}$ is read “v dot w.” Therefore for $v$ and $w$ $\in{\mathbb{R}}^n, d=v.w$ is defined as $d = \sum\limits_{i=1}^n {v_i}{w_i}$. The angle between two vectors, $\theta$, is defined by the formula:

$v.w = ||v||_2||w||_2cos\theta$

The dot product is a measure of how similarly directed the two vectors are.  In the following code we are calculating the angle between two vectors using dot product:

In [3]:
from numpy import arccos, dot

v = np.array([[10, 9, 3]])
w = np.array([[2, 5, 12]])
theta = arccos(dot(v, w.T)/(norm(v)*norm(w)))
print(f'angle between vectors {v} and {w} is {theta}')

angle between vectors [[10  9  3]] and [[ 2  5 12]] is [[0.97992471]]


Finally, the **cross product** between two vectors, $v$ and $w$, is written ${v}\times{w}$. It is defined by ${v}\times{w} = ||v||_2||w||_2\sin(\theta){n}$, where $\theta$ is the angle between the $v$ and $w$ (which can be computed from the dot product) and $n$ is a vector perpendicular to both $v$ and $w$ with unit length (i.e., the length is one). The geometric interpretation of the cross product is a vector perpendicular to both $v$ and $w$ with length equal to the area enclosed by the parallelogram created by the two vectors.

In [4]:
v = np.array([[0, 2, 0]])
w = np.array([[3, 0, 0]])
print(f'cross product between vectors {v} and {w} is {np.cross(v, w)}')

cross product between vectors [[0 2 0]] and [[3 0 0]] is [[ 0  0 -6]]


A set of vectors is said to be **linearly independent** if no vector in the set can be written as a linear combination of the other vectors in the set.  A set of vectors that is not linearly independent is linearly dependent.  In the example below, we create a new vector $x$ which is a linear combination of three other vectors:

In [5]:
v = np.array([[0, 3, 2]])
w = np.array([[4, 1, 1]])
u = np.array([[0, -2, 0]])
x = 3*v-2*w+4*u
print(x)

[[-8 -1  4]]


## Matrices

An ${m}\times{n}$ matrix is a rectangular table of numbers consisting of $m$ rows and $n$ columns. The norm of a matrix can be considered as a particular kind of vector norm.  If we treat the ${m}\times{n}$ elements of $M$ are the elements of an ${m}{n}$ dimensional vector, then you can calculate the matrix norm using the same norm function in `numpy` as that for vector.  The following code shows how this works for a 3x3 matrix $M$:

In [6]:
M = np.array([[1, 7, 5], [2, 3, 4], [5, 0, -2]])
print(f'matrix M is:\n{M}')
norm_2 = norm(M, 2)
print(f'L_2 norm of M is: {norm_2:.1f}')

matrix M is:
[[ 1  7  5]
 [ 2  3  4]
 [ 5  0 -2]]
L_2 norm of M is: 10.0


Matrix addition and scalar multiplication for matrices work the same way as for vectors.

**Matrix multiplication** between two matrices, $P$ and $Q$, is defined when $P$ is an ${m}\times{p}$ matrix and $Q$ is a ${p}\times{n}$ matrix. The result of $M=PQ$ is a matrix $M$ that is ${m}\times{n}$. The dimension with size $p$ is called the _inner matrix_ dimension, and the inner matrix dimensions must match for matrix multiplication to be defined. The dimensions $m$ and $n$ are called the _outer matrix_ dimensions. Formally, if $P$ is ${m}\times{p}$ and $Q$ is ${p}\times{n}$, then $M=PQ$ is defined as:

$M_{ij} = \sum\limits_{p=1}^nP_{ik}Q_{kj}$

The product of two matrices $P$ and $Q$ in Python is achieved by using the `dot` method in `numpy`. The transpose of a matrix is a reversal of its rows with its columns. The transpose is denoted by a superscript, $T$, such as $MT$ is the transpose of matrix $M$. In Python, the method `T` for an `numpy` `array` is used to get the transpose. For example, if $M$ is a matrix, then $M.T$ is its transpose.  The following code shows how to compute $M$, the matrix product of $P$ an $Q$ as well as $M^T$, the transpose of $M$:

In [7]:
P = np.array([[1, 7], [2, 3], [5, 0]])
Q = np.array([[2, 6, 3, 1], [1, 2, 3, 4]])
print(f'matrix P is:\n{P}')
print(f'matrix Q is:\n{Q}')
print(f'matrix M=PQ is:\n{np.dot(P, Q)}')
print(f'transpose of M is:\n{np.dot(P, Q).T}')

matrix P is:
[[1 7]
 [2 3]
 [5 0]]
matrix Q is:
[[2 6 3 1]
 [1 2 3 4]]
matrix M=PQ is:
[[ 9 20 24 29]
 [ 7 18 15 14]
 [10 30 15  5]]
transpose of M is:
[[ 9  7 10]
 [20 18 30]
 [24 15 15]
 [29 14  5]]


A **square matrix** is an ${n}\times{n}$ matrix; that is, it has the same number of rows as columns. The **determinant** is an important property of square matrices. The determinant is denoted by $det(M)$, both in mathematics and in the `numpy` `linalg` package, sometimes it is also denoted as $|M|$.  In the case of a 2×2 matrix, the determinant is:

$|M| = \begin{bmatrix}a & b\\c & d\end{bmatrix} = ad - bc$

In the case of a 3x3 matrix, the determinant is:

$|M| = \begin{bmatrix}a & b & c\\d & e & f\\g & h & i\end{bmatrix} = aei + bfg + cdh - ceg - bdi -afh$

The **identity matrix** is a square matrix with ones on the diagonal and zeros elsewhere. The identity matrix is usually denoted by 𝐼, and is analagous to the real number identity, 1. That is, multiplying any matrix by 𝐼 (of compatible size) will produce the same matrix.  The following code outlines how to calculate a determinant and identity matrix using `numpy.linalg`:

In [8]:
from numpy.linalg import det

M = np.array([[0,2,1,3], 
             [3,2,8,1], 
             [1,0,0,3],
             [0,3,2,1]])
print(f'matrix M is:\n{M}')
print(f'determinant |M| is: {det(M):.1f}')
I = np.eye(4)
print(f'identity matrix I:\n{I}')
print(f'MI:\n{np.dot(M, I)}')
assert((np.dot(M, I) == M).all)

matrix M is:
[[0 2 1 3]
 [3 2 8 1]
 [1 0 0 3]
 [0 3 2 1]]
determinant |M| is: -38.0
identity matrix I:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
MI:
[[0. 2. 1. 3.]
 [3. 2. 8. 1.]
 [1. 0. 0. 3.]
 [0. 3. 2. 1.]]


The **inverse** of a square matrix $M$ is a matrix of the same size, $N$, such that $M.N=I$. The inverse of a matrix is analagous to the inverse of real numbers. For example, the inverse of 3 is 13 because (3)(13)=1. A matrix is said to be invertible if it has an inverse. The inverse of a matrix is unique so, for an invertible matrix, there is only one inverse for that matrix. If $M$ is a square matrix, its inverse is denoted by $M^{-1}$ in mathematics, and it can be computed in Python using `numpy.linalg.inv`.  Here is an example usage:

In [9]:
from numpy.linalg import inv

print(f'matrix M is:\n{M}')
print(f'inverse of M:\n{inv(M)}')
print(f'M.inv(M):\n{np.round(np.dot(inv(M), M))}')

matrix M is:
[[0 2 1 3]
 [3 2 8 1]
 [1 0 0 3]
 [0 3 2 1]]
inverse of M:
[[-1.57894737 -0.07894737  1.23684211  1.10526316]
 [-0.63157895 -0.13157895  0.39473684  0.84210526]
 [ 0.68421053  0.18421053 -0.55263158 -0.57894737]
 [ 0.52631579  0.02631579 -0.07894737 -0.36842105]]
M.inv(M):
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0. -0.  1. -0.]
 [ 0.  0.  0.  1.]]


For a 2×2 matrix, the analytic solution of the matrix inverse is:

$M^{-1} = \begin{bmatrix}a & b\\c & d\end{bmatrix}^{-1} = \frac{1}{|M|}\begin{bmatrix}d & -b\\-c & a\end{bmatrix}$

The calculation of the matrix inverse for the analytic solution becomes complicated with increasing matrix dimension.  The process of doing so is broadly the same as learning how to solve a system of linear equations.  There are many other methods can make things easier, such as Gaussian elimination, Newton’s method and Eigendecomposition.

There are matrices that do not have inverses. These matrices are called **singular**. Matrices that do have an inverse are called **nonsingular**.  One way to determine if a matrix is singular is by computing its determinant. If the determinant is 0, then the matrix is singular; if not, the matrix is nonsingular.  Here is an example of a singular matrix:

In [10]:
P = np.array([[0,1,0],
              [0,0,0],
              [1,0,1]])
print('P:\n', P)
print('det(P):\n', det(P))

P:
 [[0 1 0]
 [0 0 0]
 [1 0 1]]
det(P):
 0.0


A matrix that is close to being singular (i.e., the determinant is close to 0) is called ill-conditioned. Although ill-conditioned matrices have inverses, they are problematic numerically in the same way that dividing a number by a very, very small number is problematic. The **condition number** is a measure of how ill-conditioned a matrix is, and it can be computed using Numpy’s function cond from linalg. The higher the condition number, the closer the matrix is to being singular.

The **rank** of an ${m}\times{n}$ matrix 𝐴 is the number of linearly independent columns or rows of $A$, and is denoted by $rank(A)$. It can be shown that the number of linearly independent rows is always equal to the number of linearly independent columns for any matrix.  A matrix is called full rank if $rank(A)=min(m,n)$. The matrix, $A$, is also full rank if all of its columns are linearly independent. An **augmented matrix** is a matrix, $A$, concatenated with a vector, $y$, and is written $[A,y]$. This is commonly read “$A$ augmented with $y$.”  You can use `np.concatenate` to concatenate the two. If $rank([A,y])=rank(A)+1$, then the vector, $y$, is “new” information. That is, it cannot be created as a linear combination of the columns in $A$. The rank is an important property of matrices because of its relationship to solutions of linear equations.

Here matrix $A=[[1,1,0],[0,1,0],[1,0,1]]$.  We compute the condition number and rank for this matrix and for $y=[[1],[2],[1]]$, we get the augmented matrix $[A, y]$.

In [11]:
from numpy.linalg import cond, matrix_rank

A = np.array([[1,1,0],
              [0,1,0],
              [1,0,1]])

print(f'matrix A is:\n{A}')
print(f'Condition number: {cond(A)}')
print(f'Rank: {matrix_rank(A)}')
y = np.array([[1], [2], [1]])
print(f'vector y is:\n{y}')
A_y = np.concatenate((A, y), axis = 1)
print(f'Augmented matrix [A,y] is:\n{A_y}')

matrix A is:
[[1 1 0]
 [0 1 0]
 [1 0 1]]
Condition number: 4.048917339522305
Rank: 3
vector y is:
[[1]
 [2]
 [1]]
Augmented matrix [A,y] is:
[[1 1 0 1]
 [0 1 0 2]
 [1 0 1 1]]


## Linear Equations

For vectors $x$ and $y$, and scalars $a$ and $b$, it is sufficient to say that a function, $F$, is a **linear transformation** if

$F(ax+by) = aF(x) + bF(y)$

It can be shown that multiplying an ${m}\times{n}$ matrix, $A$, and an  ${n}\times{1}$ vector, $v$, of compatible size is a linear transformation of $v$. Therefore from this point forward, a matrix will be synonymous with a linear transformation function.

A **system of linear equations** is a set of linear equations that share the same variables.  They can therefore be converted to a **matrix form** of ${Ax = y}$ where $A$ is an ${m}\times{n}$ matrix, $A(i,j)=a_{i,j}$, $y$ is a vector in ${\mathbb{R}}^n$, and $x$ is an unknown vector in ${\mathbb{R}}^n$.  Here is an example:

$\begin{aligned}
4x + 3y -5z = 2\\
-2x - 4y +5z = 5\\
7x + 8y = 3\\
x + 2z = -1\\
9x + y - 6z = 6
\end{aligned}$

$\begin{bmatrix}4 & 3 & -5\\-2 & -4 & 5\\7 & 8 & 0\\1 & 0 & 2\\9 & 1 & -6\end{bmatrix}
\begin{bmatrix}x\\y\\z\end{bmatrix} = 
\begin{bmatrix}2\\5\\3\\-1\\6\end{bmatrix}$

Given a system of linear equations in matrix form, $Ax=y$, where $A$ is an ${m}\times{n}$ matrix, this means there are $m$ equations and $n$ unknowns in our system. A solution to a system of linear equations is an $x$ in ${\mathbb{R}}^n$ that satisfies the matrix form equation. Depending on the values that populate $A$ and $y$, there are three distinct solution possibilities for $x$:
* **Case 1**: There is no solution for $x$. If $rank([A,y]) = rank(A) + 1$, then $y$ is linearly independent from the columns of $A$.
* **Case 2**: There is a unique solution for $x$. If $rank([A,y]) = rank(A)$, then $y$ can be written as a linear combination of the columns of $A$ and there is at least one solution for the matrix equation. For there to be only one solution, $rank(A) = n$ must also be true. 
* **Case 3**: There is an infinite number of solutions for $x$. If $rank([A,y]) = rank(A)$, then $y$ is in the range of $A$, and there is at least one solution for the matrix equation. However, if $rank(A) < n$, then there is an infinite number of solutions. 

There are a number of methods that have been developed to solve a systems of linear equations by hand when there is a unique solution. Some of the common methods include:
* The **Gauss Elimination method** turns a matrix $A$ into an upper triangular form to solve the system of equations.
* The **Gauss-Jordan Elimination method** solves the systems of equations using a procedure to turn $A$ into a diagonal form.
* The **LU decomposition method** aims to turn $A$ into the multiple of two matrices $L$ and $U$, where $L$ is a lower triangular matrix while $U$ is an upper triangular matrix.
* The **Gauss-Seidel Method** is a specific iterative method, that start with an initial guess of the solution and then repeatedly improves the solution until the change of the solution is below a threshold. 

It's easy to solve a linear equations where there is one solution using `numpy.linalg` as shown below:

In [12]:
import numpy as np

A = np.array([[4, 3, -5], 
              [-2, -4, 5], 
              [8, 8, 0]]
            )
y = np.array([[2, 5, -3]]).T
print(f'matrix A of shape (m,n) = {A.shape} is:\n{A}')
print(f'vector y is:\n{y}')
A_y = np.concatenate((A, y), axis = 1)
print(f'Augmented matrix [A,y] is:\n{A_y}')
print(f'Rank [A,y]: {matrix_rank(A_y)}')
print(f'Rank A: {matrix_rank(A)}')
print(f'Rank A == Rank [A,y] == n so there is one unique solution')
x = np.linalg.solve(A, y)
print(x)

matrix A of shape (m,n) = (3, 3) is:
[[ 4  3 -5]
 [-2 -4  5]
 [ 8  8  0]]
vector y is:
[[ 2]
 [ 5]
 [-3]]
Augmented matrix [A,y] is:
[[ 4  3 -5  2]
 [-2 -4  5  5]
 [ 8  8  0 -3]]
Rank [A,y]: 3
Rank A: 3
Rank A == Rank [A,y] == n so there is one unique solution
[[ 2.20833333]
 [-2.58333333]
 [-0.18333333]]


## Summary

* Linear algebra is the foundation of many engineering fields.
* Vectors can be considered as points in ${\mathbb{R}}^n$; addition and multiplication are defined on them, although not necessarily the same as for scalars.
* A set of vectors is linearly independent if none of the vectors can be written as a linear combination of the others.
* Matrices are tables of numbers. They have several important properties including the determinant, rank, and inverse.
* A system of linear equations can be represented by the matrix equation $Ax = y$.
* The number of solutions to a system of linear equations is related to the rank(𝐴) and the $rank([A,y])$. It can be zero, one, or infinity.
* We can solve the equations using Gauss Elimination, Gauss-Jordan Elimination, LU decomposition and Gauss-Seidel method.
* Methods exist to find matrix inversion.