# Linear Algebra Playbook

<p>
Mal Minhas, v0.1<br>
29.12.22
</p>

## Linear Algebra

Numerous problems in engineering and science can be described or approximated by linear relationships.  The study of linear relationship is contained in the field of **linear algebra**.

## Vectors

The set ${\mathbb{R}}^n$ is the set of all 𝑛-tuples of real numbers. In set notation this is ${\mathbb{R}}^n = \{(x_1,x_2,x_3,...,x_n):x_1,x_2,x_3,...,x_n{\in}{\mathbb{R}}^n\}$. For example, the set ${\mathbb{R}}^3$ represents the set of real triples, $({x},{y},{z})$ coordinates, in three-dimensional space.

A vector in ${\mathbb{R}}^n$ is an ${n}$-tuple, or point, in ${\mathbb{R}}^n$. Vectors can be written horizontally (i.e., with the elements of the vector next to each other) in a **row vector**, or vertically (i.e., with the elements of the vector on top of each other) in a **column vector**. If the context of a vector is ambiguous, it usually means the vector is a column vector. The ${i}$-th element of a vector, ${v}$, is denoted by  ${v}_i$. The transpose of a column vector is a row vector of the same length, and the transpose of a row vector is a column vector. In mathematics, the transpose is denoted by a superscript ${T}$, or  ${v}^T$. The zero vector is the vector in ${\mathbb{R}}^n$ containing all zeros.  The following Python code creates a row vector and a separate column vector, and shows the shape of the vectors.

In [51]:
import numpy as np
row_vector = np.array([[1, -5, 3, 2, 4]])
column_vector = np.array([[1], 
                          [2], 
                          [3], 
                          [4]])
print(f'{row_vector} of shape {row_vector.shape}')
print(f'{column_vector} of shape {column_vector.shape}')

[[ 1 -5  3  2  4]] of shape (1, 5)
[[1]
 [2]
 [3]
 [4]] of shape (4, 1)


The **norm** of a vector is a measure of its length. There are many ways of defining the length of a vector depending on the metric used (i.e., the distance formula chosen). The most common is called the **$L_2$ norm**, which is computed according to the distance formula you are probably familiar with from school. The $L_2$ norm of a vector $v$ is denoted by $||{v}||_2$ and $||{v}|| = \sqrt{{\sum_i}{v_i^2}}$. This is sometimes also called Euclidian length and refers to the “physical” length of a vector in 1-D, 2-D, or 3-D space. The **$L_1$ norm**, or “Manhattan Distance,” is computed as $||{v}||_1 = {\sum_i}|{v_i}|$, and is named after the grid-like road structure in New York City. The **p-norm**, $L_p$, of a vector is $\vert\vert{v}\vert\vert_p = \sqrt[p]{{\sum_i}{v_i^p}}$. The **$L_\infty$ norm**, where $p=\infty$ is written as $||𝑣||_\infty$.  The $L_\infty$ norm is equal to the maximum absolute value in $v$.

Here we transpose the row vector defined above into a column vector and calculate its $L_1$, $L_2$, and $L_\infty$ norms:

In [52]:
from numpy.linalg import norm
new_vector = row_vector.T
print(new_vector)
norm_1 = norm(new_vector, 1)
norm_2 = norm(new_vector, 2)
norm_inf = norm(new_vector, np.inf)
print('L_1 is: %.1f'%norm_1)
print('L_2 is: %.1f'%norm_2)
print('L_inf is: %.1f'%norm_inf)

[[ 1]
 [-5]
 [ 3]
 [ 2]
 [ 4]]
L_1 is: 15.0
L_2 is: 7.4
L_inf is: 5.0


**Vector addition** is defined as the pairwise addition of each of the elements of the added vectors. For example, if $v$ and $w$ are vectors in ${\mathbb{R}}^n$, then $u=v+w$ is defined as $u_i=v_i+w_i$.

**Vector multiplication** can be defined in several ways depending on the context. **Scalar multiplication** of a vector is the product of a vector and a scalar (i.e., a number in ${\mathbb{R}}^n$). Scalar multiplication is defined as the product of each element of the vector by the scalar. More specifically, if $\alpha$ is a scalar and $v$ is a vector, then 
$u = \alpha{v}$ is defined as $u_i = \alpha{v_i}$. Note that this is exactly how Python implements scalar multiplication with a vector.

The **dot product** of two vectors is the sum of the product of the respective elements in each vector and is denoted by $.$, and $v.{w}$ is read “v dot w.” Therefore for $v$ and $w$ $\in{\mathbb{R}}^n, d=v.w$ is defined as $d = \sum\limits_{i=1}^n {v_i}{w_i}$. The angle between two vectors, $\theta$, is defined by the formula:

$v.w = ||v||_2||w||_2cos\theta$

The dot product is a measure of how similarly directed the two vectors are.  In the following code we are calculating the angle between two vectors using dot product:

In [53]:
from numpy import arccos, dot

v = np.array([[10, 9, 3]])
w = np.array([[2, 5, 12]])
theta = arccos(dot(v, w.T)/(norm(v)*norm(w)))
print(theta)

[[0.97992471]]


Finally, the **cross product** between two vectors, $v$ and $w$, is written ${v}\times{w}$. It is defined by ${v}\times{w} = ||v||_2||w||_2\sin(\theta){n}$, where $\theta$ is the angle between the $v$ and $w$ (which can be computed from the dot product) and $n$ is a vector perpendicular to both $v$ and $w$ with unit length (i.e., the length is one). The geometric interpretation of the cross product is a vector perpendicular to both $v$ and $w$ with length equal to the area enclosed by the parallelogram created by the two vectors.

In [17]:
v = np.array([[0, 2, 0]])
w = np.array([[3, 0, 0]])
print(np.cross(v, w))

[[ 0  0 -6]]


A set of vectors is said to be **linearly independent** if no vector in the set can be written as a linear combination of the other vectors in the set.  A set of vectors that is not linearly independent is linearly dependent.

## Matrices

An ${m}\times{n}$ matrix is a rectangular table of numbers consisting of $m$ rows and $n$ columns. The norm of a matrix can be considered as a particular kind of vector norm, if we treat the ${m}\times{n}$ elements of $M$ are the elements of an ${m}{n}$ dimensional vector, then you can calculate the matrix norm using the same norm function in `numpy` as that for vector.

**Matrix multiplication** between two matrices, $P$ and $Q$, is defined when $P$ is an ${m}\times{p}$ matrix and $Q$ is a ${p}\times{n}$ matrix. The result of $M=PQ$ is a matrix $M$ that is ${m}\times{n}$. 

The product of two matrices $P$ and $Q$ in Python is achieved by using the `dot` method in `numpy`. The transpose of a matrix is a reversal of its rows with its columns. The transpose is denoted by a superscript, $T$, such as $MT$ is the transpose of matrix $M$. In Python, the method `T` for an `numpy` `array` is used to get the transpose. For example, if $M$ is a matrix, then $M.T$ is its transpose.

In [21]:
P = np.array([[1, 7], [2, 3], [5, 0]])
Q = np.array([[2, 6, 3, 1], [1, 2, 3, 4]])
print(P)
print(Q)
print(np.dot(P, Q))
print(np.dot(P, Q).T)

[[1 7]
 [2 3]
 [5 0]]
[[2 6 3 1]
 [1 2 3 4]]
[[ 9 20 24 29]
 [ 7 18 15 14]
 [10 30 15  5]]
[[ 9  7 10]
 [20 18 30]
 [24 15 15]
 [29 14  5]]


A **square matrix** is an 𝑛×𝑛 matrix; that is, it has the same number of rows as columns. The **determinant** is an important property of square matrices. The determinant is denoted by 𝑑𝑒𝑡(𝑀), both in mathematics and in Numpy’s linalg package, sometimes it is also denoted as |𝑀|. Some examples in the uses of a determinant will be described later.

In the case of a 2×2 matrix, the determinant is:

|𝑀|=[𝑎𝑐𝑏𝑑]=𝑎𝑑−𝑏𝑐

The **identity matrix** is a square matrix with ones on the diagonal and zeros elsewhere

In [25]:
from numpy.linalg import det

M = np.array([[0,2,1,3], 
             [3,2,8,1], 
             [1,0,0,3],
             [0,3,2,1]])
print('M:\n', M)

print('Determinant: %.1f'%det(M))
I = np.eye(4)
print('I:\n', I)
print('M*I:\n', np.dot(M, I))
assert((np.dot(M, I) == M).all)

M:
 [[0 2 1 3]
 [3 2 8 1]
 [1 0 0 3]
 [0 3 2 1]]
Determinant: -38.0
I:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
M*I:
 [[0. 2. 1. 3.]
 [3. 2. 8. 1.]
 [1. 0. 0. 3.]
 [0. 3. 2. 1.]]


The **inverse** of a square matrix 𝑀 is a matrix of the same size, 𝑁, such that 𝑀⋅𝑁=𝐼. The inverse of a matrix is analagous to the inverse of real numbers. For example, the inverse of 3 is 13 because (3)(13)=1. A matrix is said to be invertible if it has an inverse. 

In [37]:
from numpy.linalg import inv

print('Inv M:\n', inv(M))
print(np.round(np.dot(inv(M), M)))

Inv M:
 [[-1.57894737 -0.07894737  1.23684211  1.10526316]
 [-0.63157895 -0.13157895  0.39473684  0.84210526]
 [ 0.68421053  0.18421053 -0.55263158 -0.57894737]
 [ 0.52631579  0.02631579 -0.07894737 -0.36842105]]
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0. -0.  1. -0.]
 [ 0.  0.  0.  1.]]


For a 2×2 matrix, the analytic solution of the matrix inverse is:

𝑀−1=[𝑎𝑐𝑏𝑑]−1=1|𝑀|[𝑑−𝑐−𝑏𝑎]

The calculation of the matrix inverse for the analytic solution becomes complicated with increasing matrix dimension, there are many other methods can make things easier, such as Gaussian elimination, Newton’s method, Eigendecomposition and so on. We will introduce some of these methods after we learn how to solve a system of linear equations, because the process is essentially the same.



Recall that 0 has no inverse for multiplication in the real-numbers setting. Similarly, there are matrices that do not have inverses. These matrices are called **singular**. Matrices that do have an inverse are called **nonsingular**.  One way to determine if a matrix is singular is by computing its determinant. If the determinant is 0, then the matrix is singular; if not, the matrix is nonsingular.

In [38]:
P = np.array([[0,1,0],
              [0,0,0],
              [1,0,1]])
print('P:\n', P)
print('det(P):\n', det(P))

P:
 [[0 1 0]
 [0 0 0]
 [1 0 1]]
det(P):
 0.0


A matrix that is close to being singular (i.e., the determinant is close to 0) is called ill-conditioned. Although ill-conditioned matrices have inverses, they are problematic numerically in the same way that dividing a number by a very, very small number is problematic. The **condition number** is a measure of how ill-conditioned a matrix is, and it can be computed using Numpy’s function cond from linalg. The higher the condition number, the closer the matrix is to being singular.

The **rank** of an 𝑚×𝑛 matrix 𝐴 is the number of linearly independent columns or rows of 𝐴, and is denoted by rank(𝐴). It can be shown that the number of linearly independent rows is always equal to the number of linearly independent columns for any matrix. A matrix is called full rank. if rank (𝐴)=min(𝑚,𝑛). The matrix, 𝐴, is also full rank if all of its columns are linearly independent. An augmented matrix. is a matrix, 𝐴, concatenated with a vector, 𝑦, and is written [𝐴,𝑦]. This is commonly read “𝐴 augmented with 𝑦.”  You can use np.concatenate to concatenate the them. If 𝑟𝑎𝑛𝑘([𝐴,𝑦])=𝑟𝑎𝑛𝑘(𝐴)+1, then the vector, 𝑦, is “new” information. That is, it cannot be created as a linear combination of the columns in 𝐴. The rank is an important property of matrices because of its relationship to solutions of linear equations.

Here matrix 𝐴=[[1,1,0],[0,1,0],[1,0,1]].  We compute the condition number and rank for this matrix and for 𝑦=[[1],[2],[1]], we get the augmented matrix [A, y].

In [40]:
from numpy.linalg import \
             cond, matrix_rank

A = np.array([[1,1,0],
              [0,1,0],
              [1,0,1]])

print('A:\n', A)
print('Condition number:\n', cond(A))
print('Rank:\n', matrix_rank(A))
y = np.array([[1], [2], [1]])
A_y = np.concatenate((A, y), axis = 1)
print('Augmented matrix:\n', A_y)

A:
 [[1 1 0]
 [0 1 0]
 [1 0 1]]
Condition number:
 4.048917339522305
Rank:
 3
Augmented matrix:
 [[1 1 0 1]
 [0 1 0 2]
 [1 0 1 1]]


Eigenvalues: [ 2. -2.]
Eigenvectors: [[ 0.89442719 -0.89442719]
 [ 0.4472136   0.4472136 ]]


## Linear Transformations

For vectors 𝑥 and 𝑦, and scalars 𝑎 and 𝑏, it is sufficient to say that a function, 𝐹, is a linear transformation if

𝐹(𝑎𝑥+𝑏𝑦)=𝑎𝐹(𝑥)+𝑏𝐹(𝑦)

It can be shown that multiplying an 𝑚×𝑛 matrix, 𝐴, and an 𝑛×1 vector, 𝑣, of compatible size is a linear transformation of 𝑣. Therefore from this point forward, a matrix will be synonymous with a linear transformation function.

A **system of linear equations** is a set of linear equations that share the same variables.  They can therefore be converted to matrix form

$/ 4x + 3y -5z = 2 $


4𝑥+3𝑦−5𝑧 = 2
2𝑥−4𝑦+5𝑧 = 5
7𝑥+8𝑦 = 3
𝑥+2𝑧 = -1
9+𝑦−6𝑧 = 6

In [ ]:

Consider a system of linear equations in matrix form, 𝐴𝑥=𝑦, where 𝐴 is an 𝑚×𝑛 matrix. Recall that this means there are 𝑚 equations and 𝑛 unknowns in our system. A solution to a system of linear equations is an 𝑥 in ℝ𝑛 that satisfies the matrix form equation. Depending on the values that populate 𝐴 and 𝑦, there are three distinct solution possibilities for 𝑥. Either there is no solution for 𝑥, or there is one, unique solution for 𝑥, or there are an infinite number of solutions for 𝑥

Solving linear equations is easy in Python

In [42]:
import numpy as np

A = np.array([[4, 3, -5], 
              [-2, -4, 5], 
              [8, 8, 0]])
y = np.array([2, 5, -3])

x = np.linalg.solve(A, y)
print(x)

[ 2.20833333 -2.58333333 -0.18333333]


## Summary

* Linear algebra is the foundation of many engineering fields.
* Vectors can be considered as points in ℝ𝑛; addition and multiplication are defined on them, although not necessarily the same as for scalars.
* A set of vectors is linearly independent if none of the vectors can be written as a linear combination of the others.
* Matrices are tables of numbers. They have several important properties including the determinant, rank, and inverse.
* A system of linear equations can be represented by the matrix equation 𝐴𝑥=𝑦.
* The number of solutions to a system of linear equations is related to the rank(𝐴) and the rank([𝐴,𝑦]). It can be zero, one, or infinity.
* We can solve the equations using Gauss Elimination, Gauss-Jordan Elimination, LU decomposition and Gauss-Seidel method.
* Methods exist to find matrix inversion.

They have many applications, to name a few, finding the natural frequencies and mode shapes in dynamics systems, solving differential equations (we will see in later chapters), reducing the dimensions using principal components analysis, getting the principal stresses in the mechanics, and so on. Even the famous Google’s search engine algorithm - PageRank, uses the eigenvalues and eigenvectors to assign scores to the pages and rank them in the search.

In [ ]:
import numpy as np
from numpy.linalg import eig

a = np.array([[0, 4], 
              [1, 0]])
w,v=eig(a)
print('Eigenvalues:', w)
print('Eigenvectors:', v)